---
  - name: "Create Minikube cluster"
    hosts: localhost
    connection: local
    vars:
      - ansible_python_interpreter: "/usr/bin/python"
      - CLUSTER_NAME: "asgard-argocd"
      - CPU_COUNT: 4
      - MEM_COUNT: 8192
      - VOL_MOUNT: "/data"
    tasks:

    - name: "Create minikube cluster"
      delegate_to: localhost
      shell: "minikube start \
      -p {{CLUSTER_NAME}} \
      --memory {{MEM_COUNT}} \
      --cpus {{CPU_COUNT}} \
      --vm-driver=docker \
      --driver=docker"

    - name: "Enable ingress addon"
      shell: "minikube addons enable ingress -p {{CLUSTER_NAME}}"

    - name: "Change volume mount access"
      shell: ssh -i /home/pal/.minikube/machines/asgard-argocd/id_rsa docker@$(minikube ip) "echo \"chmod 777 -R {{VOL_MOUNT}} && ls -lart {{VOL_MOUNT}}\" | sudo su"
      register: result
      
    - name: "Debug volume mount message"
      ansible.builtin.debug:
        var: result