---
  - name: "Deploy jenkins to the cluster"
    hosts: localhost
    connection: local
    vars:
      - CLUSTER_NAME: "asgard-argocd"
      - NAMESPACE: "jenkins"
      - PV_NAME: "jenkins-pv"
      - PV_HOST_PATH: "/data/jenkins-volume/"
      - CHART: "jenkinsci/jenkins"
      - VOL_MOUNT: "/data"
    tasks:

    - name: Create jenkins ns
      kubernetes.core.k8s:
        state: present 
        src: "{{playbook_dir}}/configs/jenkins-ns.yaml"

    - name: Create jenkins pv
      kubernetes.core.k8s:
        state: present 
        src: "{{playbook_dir}}/configs/jenkins-pv.yaml"

    - name: Deploy jenkins with helm
      kubernetes.core.helm:
        name: jenkins
        chart_ref: "{{CHART}}"
        release_namespace: "{{NAMESPACE}}"
        values_files: "{{playbook_dir}}/configs/jenkins-values.yaml"

    - name: Change volume mount access
      shell: ssh -i /home/pal/.minikube/machines/asgard-argocd/id_rsa docker@$(minikube ip) "echo \"chmod 777 -R {{VOL_MOUNT}}/jenkins-volume && ls -lart {{VOL_MOUNT}}\" | sudo su"
      register: result

    - name: Restart jenkins pod
      kubernetes.core.k8s:
        api_version: v1
        kind: Pod
        namespace: "{{NAMESPACE}}"
        name: jenkins-0
        state: absent

    - name: Wait for jenkins pods to be ready
      kubernetes.core.k8s_info:
        kind: Pod
        wait: true
        namespace: "{{NAMESPACE}}"
        wait_sleep: 5
        wait_timeout: 150
