---
  - name: "Start Minikube cluster"
    hosts: localhost
    connection: local
    vars:
      - CLUSTER_NAME: "asgard-argocd"
    tasks:
    
    - name: "Start minikube cluster"
      delegate_to: localhost
      shell: "minikube start \
      -p {{CLUSTER_NAME}} \
      --memory {{MEM_COUNT}} \
      --cpus {{CPU_COUNT}} \
      --vm-driver=docker \
      --driver=docker"